title := MaximumWidthOfBinaryTree
all: $(title).class

$(title).class: *.java
	javac -Xlint:unchecked *.java

again:
	javac -Xlint:unchecked *.java

edit:
	emacs $(title).java

run: $(title).class
	java $(title)
