title := SetMatrixZeroes

all: $(title).class

$(title).class: $(title).java
	javac $(title).java

again:
	javac $(title).java

edit:
	emacs $(title).java

run: $(title).class
	java $(title)
